### PR TITLE
fix memory leak in referenceTable()

### LINKED ISSUE #156: Memory problem with harfbuzz 1.0.3
Scribus uses 1.2 GB of memory when it opens the test file attached to #143. And when it opens a larger file (a book consisting of 32 pages), it is killed due to out of memory.

Maybe, we need to specify minimum version of supported libharfbuzz.

This problem happens with harfbuzz 1.0.3 from openSUSE Leap 42.1. After updating libharfbuzz to 1.2.6, this problem does not reproduce. (1.2.4 also looks fine)

Note that with harfbuzz 1.2.6, it still takes several minutes to open that large file, which is maybe another issue.

The following stack trace is one obtained by sending `kill -15` just before crashes.

```
(gdb) bt
#0  0x00007ffff16f1d60 in memset () at /lib64/libc.so.6
#1  0x00007ffff16e67f2 in _int_malloc () at /lib64/libc.so.6
#2  0x00007ffff16e7732 in malloc_check () at /lib64/libc.so.6
#3  0x000000000107fcfe in referenceTable(hb_face_t*, unsigned int, void*) ()
#4  0x00007ffff6463626 in hb_ot_font_set_funcs () at /usr/lib64/libharfbuzz.so.0
#5  0x00000000010844d9 in TextShaper::shape() ()
#6  0x000000000089d8f6 in PageItem_TextFrame::layout() ()
#7  0x0000000000af90b2 in ScribusMainWindow::loadDoc(QString) ()
#8  0x0000000000afa966 in ScribusMainWindow::loadRecent(QString) ()
#9  0x0000000000b0b5bb in ScribusMainWindow::startUpDialog() ()
#10 0x0000000000b238e1 in ScribusCore::startGUI(bool, bool, bool, QString, QString) ()
#11 0x0000000000b16a5e in ScribusQApp::init() ()
#12 0x000000000104ff4e in mainApp(int, char**) ()
#13 0x00007ffff168eb05 in __libc_start_main () at /lib64/libc.so.6
#14 0x000000000061d1f7 in _start ()
```

The tested revition was 350cbe9ad2f62b5c497771f734cdf4511a30df44

### PR DESCRIPTION
**Pull request by Fahad-Alsaidi**
This should fix #156

### CODE REVIEW

File: scribus/text/textshaper.cpp [hunk 1]
```diff
@@ -312,7 +312,7 @@ static hb_blob_t *referenceTable(hb_face_t*, hb_tag_t tag, void *userData)
 		return NULL;
 	}
 
-	return hb_blob_create((const char *) buffer, length, HB_MEMORY_MODE_WRITABLE, NULL, NULL);
+	return hb_blob_create((const char *) buffer, length, HB_MEMORY_MODE_WRITABLE, buffer, free);
```
Comment (khaledhosny) [inline scribus/text/textshaper.cpp:315]: Hmm, that is how it looked before d80614cb386b676c34a0969580ccb3bf4544cca2, so it doesn’t seem to address the original issue?
